config/routes.rb
Rails.application.routes.draw do
  resources :agent_lists
  resources :tasks
  resources :tasks

end

app/models/agent_list.rb
class AgentList < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/agent_lists_controller.rb
class AgentListsController < ApplicationController
  before_action :set_agent_list, only: [:show, :edit, :update, :destroy]

  # GET /agent_lists
  # GET /agent_lists.json
  def index
    @agent_lists = AgentList.all
  end

  # GET /agent_lists/1
  # GET /agent_lists/1.json
  def show
  end

  # GET /agent_lists/new
  def new
    @agent_list = AgentList.new
  end

  # GET /agent_lists/1/edit
  def edit
  end

  # POST /agent_lists
  # POST /agent_lists.json
  def create
    @agent_list = AgentList.new(agent_list_params)

    respond_to do |format|
      if @agent_list.save
        format.html { redirect_to @agent_list, notice: 'Agent list was successfully created.' }
        format.json { render :show, status: :created, location: @agent_list }
      else
        format.html { render :new }
        format.json { render json: @agent_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agent_lists/1
  # PATCH/PUT /agent_lists/1.json
  def update
    respond_to do |format|
      if @agent_list.update(agent_list_params)
        format.html { redirect_to @agent_list, notice: 'Agent list was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent_list }
      else
        format.html { render :edit }
        format.json { render json: @agent_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agent_lists/1
  # DELETE /agent_lists/1.json
  def destroy
    @agent_list.destroy
    respond_to do |format|
      format.html { redirect_to agent_lists_url, notice: 'Agent list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent_list
      @agent_list = AgentList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_list_params
      params.require(:agent_list).permit(:name, :skills, :status, :priority, :last_task_time)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  AGENT=["Agent1","Agent2","Agent3"]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  def agent_name(skill)
     occupied_list=[]
     p skill
      AgentList.all.each do |summary|
        if summary.skills==skill
         if summary.status=="F"
            return summary.name
         elsif summary.status=="O"
            if summary.priority=="Low"
             return summary.name
            else
             occupied_list.push({:name=>summary.name,:last_task_time=>summary.last_task_time})
            end
          end
        end
      end
      if occupied_list.size>0
        sorted=occupied_list.sort_by!{|item| item[:last_task_time]} 
        a=sorted.first
        return a["name"]
      end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    name=agent_name(task_params[:skills])
    p name
    # occupied_list.values.sort
    # free_list=AgentList.find_by_status("F")
    # if free_list.size.size
    #  if summary.status.skill==task_params[:skill]
    #   return free_list.first.name
    # end
    # else
    #   occupied_list=AgentList.find_by_status("O")
    #   .map(&:agent)[0]
    # end

    # if completed_list.size>0
    #   return completed_list.map(&:agent)[0]
    # elsif started_list.size>0
    #   started_list
    # end


    @task = Task.new(task_params.merge({:current_agent=>name}))
    respond_to do |format|
      if !name.nil? && @task.save
        agent=AgentList.find_by_name(name)
        agent.update(:status=>"O")
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        p "hhhhhh"
        format.html { redirect_to "/tasks/new" ,notice: 'All Agent is occupied with this skill.Please try diffrent skill.'}
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :skills, :status, :priority, :current_agent)
    end
end

app/helpers/agent_lists_helper.rb
module AgentListsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/agent_lists/_form.html.erb
<%= form_for(@agent_list) do |f| %>
  <% if @agent_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agent_list.errors.count, "error") %> prohibited this agent_list from being saved:</h2>

      <ul>
      <% @agent_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :skills %><br>
    <%= f.text_field :skills %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :last_task_time %><br>
    <%= f.datetime_select :last_task_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agent_lists/edit.html.erb
<h1>Editing Agent List</h1>

<%= render 'form' %>

<%= link_to 'Show', @agent_list %> |
<%= link_to 'Back', agent_lists_path %>

app/views/agent_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Agent Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Skills</th>
      <th>Status</th>
      <th>Priority</th>
      
      <th>Last task time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agent_lists.each do |agent_list| %>
      <tr>
        <td><%= agent_list.name %></td>
        <td><%= agent_list.skills %></td>
        <td><%= agent_list.status %></td>
        <td><%= agent_list.priority %></td>
       
        <td><%= agent_list.last_task_time %></td>
        <td><%= link_to 'Show', agent_list %></td>
        <td><%= link_to 'Edit', edit_agent_list_path(agent_list) %></td>
        <td><%= link_to 'Destroy', agent_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agent list', new_agent_list_path %>

app/views/agent_lists/new.html.erb
<h1>New Agent List</h1>

<%= render 'form' %>

<%= link_to 'Back', agent_lists_path %>

app/views/agent_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @agent_list.name %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @agent_list.skills %>
</p>

<p>
  <strong>Status:</strong>
  <%= @agent_list.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @agent_list.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @agent_list.status %>
</p>

<p>
  <strong>Last task time:</strong>
  <%= @agent_list.last_task_time %>
</p>

<%= link_to 'Edit', edit_agent_list_path(@agent_list) %> |
<%= link_to 'Back', agent_lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agent</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
   Skill : <%= f.select :skills, options_for_select(["skill1","skill2","skill3"]) %>
  </div>
  
 <div class="field">
  Priority : <%= f.select :priority, options_for_select(["High","Low"]) %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Skills</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Current agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.skills %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.current_agent %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @task.skills %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Current agent:</strong>
  <%= @task.current_agent %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>